import {SITE,esc,getArticles,pageShell} from "./_lib/content.js";
export async function onRequestGet(){
 const type="evergreen", title="ความรู้ฟุตบอล", desc="คลังความรู้ฟุตบอล กติกา ศัพท์ สถิติ และรูปแบบการแข่งขัน อธิบายแบบอ่านง่ายและใช้เป็นข้อมูลอ้างอิงได้", canonical=`${SITE}/knowledge`;
 const items=await getArticles(type,100);
 const dynamicCards=items.map(a=>`<article class="hub-card">${a.image_url?`<img src="${esc(a.image_url)}" alt="${esc(a.title)}" loading="lazy">`:""}<div><span>${esc(a.league||title)}</span><h2><a href="/article?slug=${encodeURIComponent(a.slug)}">${esc(a.title)}</a></h2><p>${esc(a.excerpt||"")}</p></div></article>`).join("");
 const cards=dynamicCards+`<article class="hub-card"><div><span>กฎฟุตบอล</span><h2><a href="/knowledge/var-football.html">VAR คืออะไร ทำงานอย่างไร</a></h2><p>VAR ย่อมาจาก Video Assistant Referee หรือผู้ช่วยผู้ตัดสินวิดีโอ เป็นระบบที่ช่วยให้ทีมผู้ตัดสินตรวจสอบเหตุการณ์สำคัญจากภาพวิดีโอ เพื่อลดความผิดพลาดที่ชัดเจนในการตัดสิน</p></div></article><article class="hub-card"><div><span>กฎฟุตบอล</span><h2><a href="/knowledge/offside-rule.html">กฎล้ำหน้าฟุตบอลฉบับเข้าใจง่าย</a></h2><p>การอยู่ในตำแหน่งล้ำหน้าเพียงอย่างเดียวยังไม่ถือว่าเป็นความผิด ผู้เล่นจะถูกลงโทษเมื่ออยู่ในตำแหน่งล้ำหน้าในขณะที่เพื่อนร่วมทีมเล่นหรือสัมผัสบอล แล้วเข้ามามีส่วนร่วมกับการเล่นตามเงื่อนไขของกติกา</p></div></article><article class="hub-card"><div><span>พื้นฐานฟุตบอล</span><h2><a href="/knowledge/football-table-points.html">ตารางคะแนนฟุตบอลคิดคะแนนอย่างไร</a></h2><p>ลีกฟุตบอลส่วนใหญ่ใช้ระบบคะแนนพื้นฐานที่เข้าใจง่าย: ชนะได้ 3 คะแนน เสมอได้ 1 คะแนน และแพ้ได้ 0 คะแนน คะแนนสะสมจากทุกนัดจะถูกนำมาเรียงอันดับในตาราง</p></div></article><article class="hub-card"><div><span>สถิติฟุตบอล</span><h2><a href="/knowledge/goal-difference.html">ผลต่างประตูได้เสียคืออะไร</a></h2><p>ผลต่างประตูได้เสีย หรือ Goal Difference คำนวณจากจำนวนประตูที่ทีมยิงได้ ลบด้วยจำนวนประตูที่เสีย เช่น ยิงได้ 25 ประตูและเสีย 18 ประตู จะมีผลต่างประตูได้เสีย +7</p></div></article><article class="hub-card"><div><span>รายการแข่งขัน</span><h2><a href="/knowledge/champions-league-format.html">Champions League รูปแบบการแข่งขันเป็นอย่างไร</a></h2><p>ยูฟ่า แชมเปียนส์ลีกเป็นการแข่งขันสโมสรระดับยุโรปที่มีทั้งรอบคัดเลือกและรอบการแข่งขันหลัก โดยตั้งแต่ฤดูกาล 2024/25 รอบหลักเปลี่ยนจากระบบแบ่งกลุ่มแบบเดิมเป็นลีกเฟสที่มี 36 ทีม</p></div></article><article class="hub-card"><div><span>กฎฟุตบอล</span><h2><a href="/knowledge/yellow-red-cards.html">ใบเหลืองและใบแดงมีกฎอย่างไร</a></h2><p>ใบเหลืองใช้เป็นการคาดโทษผู้เล่นหรือเจ้าหน้าที่ทีมจากพฤติกรรมที่เข้าข่ายตามกติกา เช่น การประพฤติไม่เหมาะสม การถ่วงเวลา การไม่รักษาระยะในบางสถานการณ์ หรือการทำผิดซ้ำ ๆ</p></div></article><article class="hub-card"><div><span>กฎฟุตบอล</span><h2><a href="/knowledge/extra-time-penalty-shootout.html">Extra Time กับการดวลจุดโทษต่างกันอย่างไร</a></h2><p>Extra Time หรือการต่อเวลาพิเศษ ใช้ในบางการแข่งขันแบบแพ้คัดออกเมื่อผลยังเสมอกันหลังเวลาปกติ โดยทั่วไปแบ่งเป็นสองช่วง ช่วงละ 15 นาที แต่ต้องยึดระเบียบของรายการเป็นหลัก</p></div></article><article class="hub-card"><div><span>สถิติฟุตบอล</span><h2><a href="/knowledge/how-to-read-football-stats.html">วิธีอ่านสถิติฟุตบอลก่อนการแข่งขัน</a></h2><p>การอ่านสถิติก่อนการแข่งขันควรดูหลายตัวแปรร่วมกัน ไม่ควรตัดสินจากตัวเลขค่าเดียว เริ่มจากฟอร์มช่วงล่าสุด จำนวนประตูได้และเสีย คุณภาพคู่แข่ง และความแตกต่างระหว่างเกมเหย้ากับเกมเยือน</p></div></article>`;
 const schema={"@context":"https://schema.org","@type":"CollectionPage","name":title,"url":canonical,"description":desc,"isPartOf":{"@type":"WebSite","name":"HN FOOTBALL SCORE","url":`${SITE}/`}};
 const body=`<main class="article-shell"><a class="back" href="/">← กลับหน้าหลัก</a><section class="hub-head"><div class="kicker">HN FOOTBALL SCORE</div><h1>${title}</h1><p>${desc}</p></section><section class="hub-list">${cards}</section></main>`;
 return new Response(pageShell({title:`${title} | HN FOOTBALL SCORE`,description:desc,canonical,body,schema}),{headers:{"Content-Type":"text/html; charset=UTF-8","Cache-Control":"public, max-age=0, s-maxage=180"}})
}
