const CONTENT_API="https://balltoday-content-api.noppdsoma.workers.dev";
const SITE_URL="https://www.fb55vip.com";
const escapeHtml=(value="")=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
const safeUrl=value=>{try{const url=new URL(value);return ["http:","https:"].includes(url.protocol)?url.toString():""}catch{return""}};
const socialDetails=value=>{const host=new URL(value).hostname.toLowerCase();if(host.includes("facebook"))return["facebook","f","Facebook"];if(host.includes("line.me"))return["line","L","LINE"];if(host.includes("instagram"))return["instagram","◎","Instagram"];if(host.includes("tiktok"))return["tiktok","♪","TikTok"];if(host.includes("youtube")||host.includes("youtu.be"))return["youtube","▶","YouTube"];if(host==="x.com"||host.endsWith(".x.com")||host.includes("twitter"))return["x","X","X"];return["other","↗",host]};

function page(author,articles,username){
  const canonical=`${SITE_URL}/author/${encodeURIComponent(username)}`,name=author.display_name||author.username||"ผู้เขียน",sameAs=Array.isArray(author.same_as)?author.same_as.map(safeUrl).filter(Boolean):[];
  const schema={"@context":"https://schema.org","@type":"ProfilePage",mainEntity:{"@type":"Person",name,url:canonical,image:safeUrl(author.avatar_url)||undefined,description:author.bio||undefined,sameAs:sameAs.length?sameAs:undefined}};
  const cards=articles.map(item=>`<article class="author-article"><a href="/article?slug=${encodeURIComponent(item.slug)}">${item.image_url?`<img src="${escapeHtml(item.image_url)}" alt="${escapeHtml(item.title)}" loading="lazy">`:""}<div><span>${escapeHtml(item.league||item.content_type||"บทความ")}</span><h2>${escapeHtml(item.title||"")}</h2><p>${escapeHtml(item.excerpt||"")}</p></div></a></article>`).join("");
  const links=sameAs.map(url=>{const [platform,mark,label]=socialDetails(url);return `<a href="${escapeHtml(url)}" target="_blank" rel="me noopener noreferrer"><span class="social-icon social-icon--${platform}" aria-hidden="true">${mark}</span><span>${escapeHtml(label)}</span></a>`}).join("");
  return `<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow,max-image-preview:large"><title>${escapeHtml(name)} | ผู้เขียน HN FOOTBALL SCORE</title><meta name="description" content="${escapeHtml(author.bio||`รวมบทความของ ${name} จาก HN FOOTBALL SCORE`)}"><link rel="canonical" href="${escapeHtml(canonical)}"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,"\\u003c")}</script><link rel="stylesheet" href="/assets/css/article-v18.css"><link rel="stylesheet" href="/assets/css/author-profile.css?v=20260825-1"></head><body><header class="article-header"><a href="/">⚽ <strong>HN <span>FOOTBALL SCORE</span></strong></a></header><main class="author-shell"><nav><a href="/">หน้าแรก</a> › ผู้เขียน › ${escapeHtml(name)}</nav><section class="author-hero">${author.avatar_url?`<img src="${escapeHtml(author.avatar_url)}" alt="${escapeHtml(name)}" width="128" height="128">`:""}<div><p>ผู้เขียน HN FOOTBALL SCORE</p><h1>${escapeHtml(name)}</h1>${author.bio?`<p>${escapeHtml(author.bio)}</p>`:""}<div class="author-links">${links}</div></div></section><section><h2>บทความทั้งหมด</h2><div class="author-grid">${cards||"<p>ยังไม่มีบทความที่เผยแพร่</p>"}</div></section></main></body></html>`;
}
export async function onRequest(context){const username=String(context.params.username||"").trim();if(!username)return new Response("Not found",{status:404});try{const response=await fetch(`${CONTENT_API}/api/authors/${encodeURIComponent(username)}`,{headers:{Accept:"application/json"}});if(!response.ok)return new Response("ไม่พบผู้เขียน",{status:404,headers:{"content-type":"text/plain; charset=UTF-8"}});const data=await response.json();return new Response(page(data.author,data.articles||[],username),{headers:{"content-type":"text/html; charset=UTF-8","cache-control":"public, max-age=60, s-maxage=300","x-content-type-options":"nosniff"}})}catch{return new Response("เกิดข้อผิดพลาด",{status:500,headers:{"content-type":"text/plain; charset=UTF-8"}})}}
