"use strict";
const CFG=window.BALLTODAY_CONFIG;const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
let liveMatches=[],deferredPrompt=null,currentLeague=CFG.defaultLeague,currentDateOffset=0;
async function getJSON(path){const c=new AbortController();const t=setTimeout(()=>c.abort(),CFG.requestTimeout);try{const r=await fetch(CFG.apiBaseUrl+path,{headers:{Accept:"application/json"},signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function setStatus(text,ok=true){$("#systemStatus").textContent=text;$("#updatedAt").textContent=`• ${new Date().toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit"})}`;$(".status-dot").style.background=ok?"var(--green)":"var(--red)"}
function team(x,side){const t=x.teams?.[side]||{};return `<div class="team ${side==='away'?'away':''}">${side==='away'?`<span>${esc(t.name||'-')}</span><img src="${esc(t.logo||'')}" alt="">`:`<img src="${esc(t.logo||'')}" alt=""><span>${esc(t.name||'-')}</span>`}</div>`}
function matchCard(x){const f=x.fixture||{},g=x.goals||{},l=x.league||{};return `<article class="match-card"><div class="match-top"><span>${esc(l.name||'ฟุตบอล')}</span><span class="pill red">${esc(f.status?.short||'LIVE')} ${f.status?.elapsed??''}${f.status?.elapsed?"'":""}</span></div><div class="teams-row">${team(x,'home')}<div class="score">${g.home??0} - ${g.away??0}</div>${team(x,'away')}</div><div class="match-footer"><span>${esc(f.venue?.name||'')}</span><button class="event-btn" data-events="${esc(f.id||'')}">เหตุการณ์</button></div></article>`}
function heroCard(x){if(!x)return `<div class="empty">ยังไม่มีคู่ที่กำลังแข่งขัน</div>`;const g=x.goals||{};return `<div class="teams-row">${team(x,'home')}<div class="score">${g.home??0} - ${g.away??0}</div>${team(x,'away')}</div><div class="match-footer"><span>${esc(x.league?.name||'')}</span><span>${esc(x.fixture?.status?.elapsed??'')} ${x.fixture?.status?.elapsed?"นาที":""}</span></div>`}
async function loadLive(){try{const d=await getJSON('/api/live');liveMatches=d.response||[];renderLive('all');$("#heroLive").innerHTML=heroCard(liveMatches[0]);setStatus(`ออนไลน์ • ${liveMatches.length} คู่กำลังแข่งขัน`)}catch(e){$("#liveGrid").innerHTML=`<div class="error">โหลดผลบอลสดไม่สำเร็จ</div>`;setStatus('เชื่อมต่อ API ไม่สำเร็จ',false)}}
function renderLive(mode){const a=mode==='important'?liveMatches.filter(x=>CFG.importantLeagues.includes(x.league?.id)):liveMatches;$("#liveGrid").innerHTML=a.length?a.slice(0,18).map(matchCard).join(''):`<div class="empty">ขณะนี้ยังไม่มีการแข่งขันสด</div>`;$$('[data-events]').forEach(b=>b.onclick=()=>loadEvents(b.dataset.events))}
function dateISO(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(d)}
async function loadFixtures(){try{const d=await getJSON(`/api/fixtures?date=${dateISO(currentDateOffset)}`);const a=d.response||[];$("#fixturesList").innerHTML=a.length?a.slice(0,40).map(x=>{const f=x.fixture||{},t=x.teams||{},l=x.league||{};const tm=new Date(f.date).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Bangkok'});return `<div class="fixture-row"><span class="fixture-time">${tm}</span><span>${esc(t.home?.name||'-')}</span><b>VS</b><span class="fixture-team away">${esc(t.away?.name||'-')}</span><span class="league-name">${esc(l.name||'')}</span></div>`}).join(''):`<div class="empty">ไม่พบโปรแกรมการแข่งขัน</div>`}catch(e){$("#fixturesList").innerHTML=`<div class="error">โหลดโปรแกรมบอลไม่สำเร็จ</div>`}}
async function loadStandings(){try{const d=await getJSON(`/api/standings?league=${currentLeague}&season=${CFG.season}`);const a=d.response?.[0]?.league?.standings?.[0]||[];$("#standingsBody").innerHTML=a.length?a.map(x=>`<tr><td>${x.rank}</td><td><span class="team-cell"><img src="${esc(x.team?.logo||'')}" alt="">${esc(x.team?.name||'')}</span></td><td>${x.all?.played??0}</td><td>${x.goalsDiff??0}</td><td><b>${x.points??0}</b></td></tr>`).join(''):`<tr><td colspan="5">ไม่มีข้อมูลฤดูกาลนี้</td></tr>`}catch(e){$("#standingsBody").innerHTML=`<tr><td colspan="5" class="error">โหลดตารางคะแนนไม่สำเร็จ</td></tr>`}}
async function loadScorers(){try{const d=await getJSON(`/api/topscorers?league=${currentLeague}&season=${CFG.season}`);const a=d.response||[];$("#scorersList").innerHTML=a.length?a.slice(0,10).map((x,i)=>{const p=x.player||{},s=x.statistics?.[0]||{};return `<div class="rank-row"><b>${i+1}</b><img src="${esc(p.photo||'')}" alt=""><span>${esc(p.name||'')}<small>${esc(s.team?.name||'')}</small></span><b>${s.goals?.total??0}</b></div>`}).join(''):`<div class="empty">ไม่มีข้อมูลดาวซัลโว</div>`}catch(e){$("#scorersList").innerHTML=`<div class="error">แพ็กเกจหรือฤดูกาลนี้อาจไม่รองรับดาวซัลโว</div>`}}
function analysisCard(x){const t=x.teams||{},f=x.fixture||{},l=x.league||{};const h=x.predictions?.winner?.name||'ยังไม่ระบุ';const pct=x.predictions?.percent||{};const confidence=Math.max(parseInt(pct.home)||0,parseInt(pct.draw)||0,parseInt(pct.away)||0);return `<article class="analysis-card"><span class="pill">${esc(l.name||'ฟุตบอล')}</span><h3>${esc(t.home?.name||'-')} พบ ${esc(t.away?.name||'-')}</h3><p>${esc(x.predictions?.advice||'วิเคราะห์จากฟอร์มและสถิติของทีม')}</p><div class="confidence"><span>แนวโน้ม: ${esc(h)}</span><b>${confidence||'-'}%</b></div><small class="note">Fixture ID: ${esc(f.id||'')}</small></article>`}
async function loadAnalysis(){try{const d=await getJSON(`/api/fixtures?date=${dateISO(0)}`);const fixtures=(d.response||[]).slice(0,6);const results=[];for(const x of fixtures.slice(0,3)){try{const p=await getJSON(`/api/predictions?fixture=${x.fixture.id}`);if(p.response?.[0])results.push(p.response[0])}catch{}}$("#analysisGrid").innerHTML=results.length?results.map(analysisCard).join(''):`<div class="empty">ยังไม่มีข้อมูลวิเคราะห์สำหรับคู่วันนี้</div>`}catch(e){$("#analysisGrid").innerHTML=`<div class="error">โหลดบทวิเคราะห์ไม่สำเร็จ</div>`}}
async function loadEvents(id){const box=$("#eventsList");box.innerHTML=`<div class="skeleton"></div>`;try{const d=await getJSON(`/api/events?fixture=${id}`);const a=d.response||[];box.innerHTML=a.length?a.map(x=>{const icon=x.type==='Card'?(x.detail?.includes('Red')?'🟥':'🟨'):x.type==='Goal'?'⚽':'•';return `<div class="event-row"><span>${x.time?.elapsed??'-'}'</span><span><span class="event-icon">${icon}</span> ${esc(x.player?.name||x.team?.name||'')}</span><b>${esc(x.detail||x.type||'')}</b></div>`}).join(''):`<div class="empty">ยังไม่มีเหตุการณ์</div>`;loadOdds(id)}catch(e){box.innerHTML=`<div class="error">โหลดเหตุการณ์ไม่สำเร็จ</div>`}}
async function loadOdds(id){const box=$("#oddsList");box.innerHTML=`<div class="skeleton"></div>`;try{const d=await getJSON(`/api/odds?fixture=${id}`);const bets=d.response?.[0]?.bookmakers?.[0]?.bets||[];box.innerHTML=bets.length?bets.slice(0,5).map(b=>`<div class="odds-row"><b>${esc(b.name||'ตลาด')}</b><span>${(b.values||[]).slice(0,3).map(v=>`${esc(v.value)} ${esc(v.odd)}`).join(' • ')}</span></div>`).join(''):`<div class="empty">แพ็กเกจ API อาจไม่รองรับราคาบอลคู่นี้</div>`}catch(e){box.innerHTML=`<div class="error">ไม่สามารถโหลดราคาบอลได้</div>`}}
async function searchAll(q){const section=$("#searchResultsSection"),box=$("#searchResults");section.hidden=false;section.scrollIntoView({behavior:'smooth'});box.innerHTML=`<div class="skeleton"></div>`;try{const [teams,leagues]=await Promise.all([getJSON(`/api/search/teams?q=${encodeURIComponent(q)}`),getJSON(`/api/search/leagues?q=${encodeURIComponent(q)}`)]);const items=[];(teams.response||[]).forEach(x=>items.push(`<article class="search-item"><img src="${esc(x.team?.logo||'')}" alt=""><h3>${esc(x.team?.name||'')}</h3><p>${esc(x.team?.country||'')}</p></article>`));(leagues.response||[]).forEach(x=>items.push(`<article class="search-item"><img src="${esc(x.league?.logo||'')}" alt=""><h3>${esc(x.league?.name||'')}</h3><p>${esc(x.country?.name||'')}</p></article>`));box.innerHTML=items.length?items.join(''):`<div class="empty">ไม่พบผลการค้นหา</div>`}catch(e){box.innerHTML=`<div class="error">ค้นหาไม่สำเร็จ</div>`}}
function bind(){const mb=$("#menuBtn"),nav=$("#mainNav");mb.onclick=()=>{const open=nav.classList.toggle('open');mb.setAttribute('aria-expanded',open)};$$('[data-live-filter]').forEach(b=>b.onclick=()=>{$$('[data-live-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLive(b.dataset.liveFilter)});$$('[data-day]').forEach(b=>b.onclick=()=>{$$('[data-day]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentDateOffset=Number(b.dataset.day);loadFixtures()});$("#leagueSelect").onchange=e=>{currentLeague=Number(e.target.value);loadStandings();loadScorers()};$("#searchForm").onsubmit=e=>{e.preventDefault();const q=$("#searchInput").value.trim();if(q.length>=3)searchAll(q)};$("#closeSearch").onclick=()=>$("#searchResultsSection").hidden=true;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").hidden=true}}}
async function init(){bind();if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js');await Promise.allSettled([loadLive(),loadFixtures(),loadStandings(),loadScorers(),loadAnalysis()]);const ms=CFG.refresh[CFG.mode]||CFG.refresh.free;setInterval(()=>{loadLive();loadFixtures()},ms)}document.addEventListener('DOMContentLoaded',init);
